export interface PermissionProfileOptions { allowedDomains?: string[] }

export function renderPermissionProfiles(options: PermissionProfileOptions = {}): string {
  const domains = [...new Set(options.allowedDomains ?? [])].filter((domain) => /^[A-Za-z0-9.-]+$/.test(domain));
  return [
    "# Generated by WinYOLO 0.3. Import or copy these profiles into Codex config.toml.",
    "[profiles.winyolo-safe]", 'approval_policy = "on-request"', 'sandbox_mode = "workspace-write"',
    "", "[profiles.winyolo-yolo]", 'approval_policy = "never"', 'sandbox_mode = "workspace-write"',
    "", "[sandbox_workspace_write]", `network_access = ${domains.length ? "true" : "false"}`,
    ...(domains.length ? ["", "[network]", 'mode = "proxy"', `allowed_domains = [${domains.map((domain) => `"${domain}"`).join(", ")}]`] : []),
    "", "# Secrets are additionally withheld by isolated-worktree preparation and hook policy.", "",
  ].join("\n");
}
